=== SteelCompendium/data-sdk-npm/src/schema/feature.schema.json
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "$id": "feature.schema.json-3.0.0",
  "title": "Steel Compendium Feature",
  "type": "object",
  "required": [
    "type",
    "feature_type",
    "effects"
  ],
  "properties": {
    "name": {
      "type": "string",
      "description": "The title or description of the feature"
    },
    "icon": {
      "type": "string",
      "description": "The icon of the feature (ex: \"🏹\")"
    },
    "type": {
      "type": "string",
      "description": "Must always be 'feature'"
    },
    "feature_type": {
      "type": "string",
      "description": "The type of the feature (ability or trait)"
    },
    "usage": {
      "type": "string",
      "description": "Usage (e.g., \"Action\", \"Maneuver\", \"Triggered Action\", \"Villain Action 1\")"
    },
    "cost": {
      "type": "string",
      "description": "Cost to use the feature (e.g., \"5 Essence\", \"Signature\", \"2 Malice\")"
    },
    "ability_type": {
      "type": "string",
      "description": "Type of the ability (Signature or Heroic)"
    },
    "keywords": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "Keywords associated with the feature (e.g., [\"Magic\",\"Earth\",\"Melee\"])"
    },
    "distance": {
      "type": "string",
      "description": "Distance or area (e.g., \"Ranged 5\", \"2 burst\", \"Melee 1\")"
    },
    "target": {
      "type": "string",
      "description": "Who or what is targeted (e.g., \"All enemies\", \"One creature\", \"Self\")"
    },
    "trigger": {
      "type": "string",
      "description": "Trigger condition for triggered actions"
    },
    "effects": {
      "$ref": "#/definitions/effectsArray"
    },
    "flavor": {
      "type": "string",
      "description": "Flavor text of the feature"
    },
    "metadata": {
      "type": "object",
      "description": "Metadata for the feature, to be converted to frontmatter in markdown. This field contains key-value pairs that will be rendered as YAML frontmatter.",
      "additionalProperties": true
    }
  },
  "unevaluatedProperties": false,
  "definitions": {
    "effectsArray": {
      "type": "array",
      "minItems": 1,
      "description": "List of effects (flexible formats)",
      "items": {
        "$ref": "#/definitions/effect"
      }
    },
    "effect": {
      "type": "object",
      "required": [
      ],
      "properties": {
        "name": {
          "type": "string",
          "description": "Name of the effect"
        },
        "cost": {
          "type": "string",
          "description": "Cost to trigger this effect"
        },
        "effect": {
          "type": "string",
          "description": "Effect expression (e.g., \"All targets make a Might test.\")"
        },
        "roll": {
          "type": "string",
          "description": "Power Roll expression (e.g., \"2d10 + 3\")"
        },
        "features": {
          "type": "array",
          "description": "List of features granted by the effect",
          "items": {
            "$ref": "feature.schema.json-3.0.0#"
          }
        },
        "tier1": { "type": "string"},
        "tier2": { "type": "string"},
        "tier3": { "type": "string"},
        "t1": { "type": "string"},
        "t2": { "type": "string"},
        "t3": { "type": "string"},
        "crit": { "type": "string"},
        "11 or lower": { "type": "string"},
        "12-16": { "type": "string"},
        "17+": { "type": "string"},
        "nat 19-20": { "type": "string"}
      },
      "anyOf": [
        { "required": ["effect"] },
        { "required": ["roll", "tier1", "tier2", "tier3"] },
        { "required": ["roll", "t1", "t2", "t3"] },
        { "required": ["roll", "11 or lower", "12-16", "17+"] }
      ]
    }
  }
}

=== SteelCompendium/data-sdk-npm/src/__tests__/data/feature/dto-json/divine_dragon.json
{
  "type": "feature",
  "feature_type": "ability",
  "name": "DIVINE DRAGON",
  "cost": "11 PIETY",
  "flavor": "From nothing but divine will, you create a powerful ally.",
  "keywords": [
    "Magic",
    "Ranged"
  ],
  "usage": "Main Action",
  "distance": "Ranged 10",
  "target": "Special",
  "effects": [
    {
      "name": "Effect",
      "effect": "You conjure a size 4 dragon that appears in an unoccupied space within distance. The dragon has speed 6 and can fly, stability 4, 100 Stamina, immunity all to fire damage, and uses your characteristics. The dragon disappears at the end of the encounter, if their Stamina drops to 0, or if you are dying.\nOn subsequent turns, you can use a main action to command the dragon to breathe magic fire in a 3 cube within 1 square of them. Make the following power roll targeting each enemy in the area."
    },
    {
      "roll": "Power Roll + Intuition",
      "t1": "5 fire damage",
      "t2": "9 fire damage",
      "t3": "12 fire damage"
    },
    {
      "name": "Effect",
      "effect": "Additionally, you can use a maneuver to move the dragon up to their speed, or to make a melee weapon strike with their claw against an adjacent creature or object. The dragon can also make this strike as a free strike."
    },
    {
      "roll": "Power Roll + Intuition",
      "t1": "3 + I damage",
      "t2": "5 + I damage",
      "t3": "8 + I damage"
    }
  ]
}

=== SteelCompendium/data-sdk-npm/src/__tests__/data/feature/dto-json/this_is_an_h8_header.json
{
  "type": "feature",
  "feature_type": "ability",
  "name": "This is an H8 Header",
  "cost": "8 Energy",
  "flavor": "You warp reality to grow a header for just a moment and make a single devastating attack.",
  "keywords": [
    "Area",
    "Psionic"
  ],
  "usage": "Main action",
  "distance": "Ranged 10",
  "target": "One creature or object",
  "metadata": {
    "class": "introduction",
    "cost": "8 Energy",
    "level": 1,
    "name": "This Is An H8 Header",
    "type": "ability"
  },
  "effects": [
    {
      "roll": "Power Roll + Agility",
      "t1": "12 psychic damage; push 3",
      "t2": "17 psychic damage; push 5",
      "t3": "23 psychic damage; push 7"
    }
  ]
}

=== SteelCompendium/data-sdk-npm/src/__tests__/data/feature/dto-json/unquiet_ground.json
{
  "type": "feature",
  "feature_type": "ability",
  "name": "UNQUIET GROUND",
  "flavor": "A sudden storm of detritus assaults your foes and leaves them struggling to move.",
  "keywords": [
    "Area",
    "Earth",
    "Magic",
    "Ranged"
  ],
  "usage": "Main Action",
  "distance": "2 cube within 10",
  "target": "Each enemy in the area",
  "effects": [
    {
      "roll": "Power Roll + Reason",
      "tier1": "2 damage",
      "tier2": "5 damage",
      "tier3": "7 damage"
    },
    {
      "name": "Effect",
      "effect": "The ground beneath the area is difficult terrain for enemies."
    }
  ]
}

=== SteelCompendium/data-sdk-npm/src/__tests__/data/feature/dto-json/ray_of_agonizing_self_reflection.json
{
  "type": "feature",
  "feature_type": "ability",
  "name": "RAY OF AGONIZING SELF-REFLECTION",
  "flavor": "You inflict pain and doubt in equal measure.",
  "keywords": [
    "Magic",
    "Ranged",
    "Strike",
    "Void"
  ],
  "usage": "Main Action",
  "distance": "Ranged 10",
  "target": "One creature or object",
  "effects": [
    {
      "roll": "Power Roll + Reason",
      "t1": "2 + R corruption damage; R < weak, slowed (save ends)",
      "t2": "4 + R corruption damage; R < average, slowed (save ends)",
      "t3": "6 + R corruption damage; R < strong, slowed (save ends)"
    }
  ]
}

=== SteelCompendium/data-sdk-npm/src/__tests__/data/feature/dto-json/2nd Level Exorcist Ability.json
{
  "type": "feature",
  "feature_type": "trait",
  "name": "2nd-Level Exorcist Ability",
  "effects": [
    {
      "effect": "Choose one of the following abilities.",
      "features": [
        {
          "type": "feature",
          "feature_type": "ability",
          "name": "It Is Justice You Fear",
          "cost": "5 Wrath",
          "flavor": "I am but a vessel. Your own deeds weigh upon you.",
          "icon": "üèπ",
          "keywords": [
            "Magic",
            "Ranged",
            "Strike"
          ],
          "usage": "Main action",
          "distance": "Ranged 10",
          "target": "One creature",
          "effects": [
            {
              "roll": "Power Roll + Might",
              "tier1": "8 + M holy damage; P < WEAK, frightened (save ends)",
              "tier2": "12 + M holy damage; P < AVERAGE, frightened (save ends)",
              "tier3": "15 + M holy damage; P < STRONG, frightened (save ends)"
            },
            {
              "name": "Effect",
              "effect": "If the target is already frightened of you or another creature and this ability would frighten them again, they instead take psychic damage equal to twice your Presence score."
            }
          ]
        },
        {
          "type": "feature",
          "feature_type": "ability",
          "name": "Revelator",
          "cost": "5 Wrath",
          "flavor": "You channel holy energy to harm unbelievers and reveal those hidden from your judgment.",
          "icon": "‚ùáÔ∏è",
          "keywords": [
            "Area",
            "Magic"
          ],
          "usage": "Maneuver",
          "distance": "3 burst",
          "target": "Each enemy in the area",
          "effects": [
            {
              "name": "Effect",
              "effect": "Each target takes holy damage equal to twice your Presence score. Additionally, each hidden target is automatically revealed and can't become hidden again until the start of your next turn. You can then use your Judgment ability against one target as a free triggered action."
            }
          ]
        }
      ]
    }
  ]
}
